version: '3.8'

services:
  web:
    build: .
    ports:
      - "5005:5005"
    volumes:
      - .:/app
      - ./2025:/app/2025
    environment:
      - TZ=Europe/Bucharest
    restart: unless-stopped
